<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Provides source generators for Harp device firmware and software interface.</Description>
    <PackageTags>$(PackageTags) Device Firmware Interface</PackageTags>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <T4Preprocess Include="*.tt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="core.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bonsai.Harp" Version="3.5.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="T4.BuildTools" Version="3.0.0" />
  </ItemGroup>

</Project>